In [80]:
# import pyodbc
import pandas as pd
import subprocess
from csv import reader
import re

In [62]:
fname = "/Users/shua784/Dropbox/PNNL/Projects/Columbia_Basin/Yakima/data/SSURGO/SWAT_US_SSURGO_Soils.mdb"
fname_csv = "/Users/shua784/Dropbox/PNNL/Projects/Columbia_Basin/Yakima/data/SSURGO/SWAT_US_SSURGO_Soils.csv"

# Read MDF files 

Following [Reading MS Access MDB Files on Mac](https://medium.com/@wenyu.z/reading-ms-access-mdb-files-on-mac-969a176baa7a).

Pre-requsite: `mdbtools` and/or `meza`.

In [94]:
def show_tables(path='<file_name>.mdb'):
    tables = subprocess.check_output(["mdb-tables", path])
    return tables.decode().split()

def show_data(path='<file_name>.mdb', table='<table_name>'):
    tables = subprocess.check_output(["mdb-export", path, table])
    return tables.decode().split('\n')
 
def convert_df(path, table):
    d = show_data(path, table)
    columns = d[0].split(',')
#     data = [i.split(',')[:len(columns)] for i in d[1:]]
    # use more smarty way to separate the column data
    data = [re.findall(r'(?:,|\n|^)("(?:(?:"")*[^"]*)*"|[^",\n]*|(?:\n|$))', i)[:len(columns)] for i in d[1:]]
    df = pd.DataFrame(columns=columns, data=data)
    return df

In [17]:
tables = show_tables(fname)
tables

['SSURGO_Soils']

In [87]:
df = convert_df(fname, table=tables[0])

In [89]:
df

,OBJECTID,MUID,SEQN,SNAM,S5ID,CMPPCT,NLAYERS,HYDGRP,SOL_ZMX,ANION_EXCL,...,SOL_PH3,SOL_PH4,SOL_PH5,SOL_PH6,SOL_PH7,SOL_PH8,SOL_PH9,SOL_PH10,HYDGRP_ORIG,Notes
0,30,"""49315""",49315,"""Aquic Eutrocryepts""","""AK615""",4.5000000000000000e+01,3,"""B""",1.5200000000000000e+03,5.0000000000000000e-01,...,6.7000000000000002e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,"""B""",
1,803,"""50154""",50154,"""Entisols""","""AK646""",5.5000000000000000e+01,3,"""C""",1.5200000000000000e+03,5.0000000000000000e-01,...,5.9000000000000004e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,"""C""",
2,804,"""50155""",50155,"""Typic Cryaquents""","""AK646""",5.5000000000000000e+01,3,"""D""",1.5200000000000000e+03,5.0000000000000000e-01,...,5.5999999999999996e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,"""D""",
3,811,"""50163""",50163,"""Cryohemists""","""AK646""",8.5000000000000000e+01,5,"""D""",1.5200000000000000e+03,5.0000000000000000e-01,...,5.5000000000000000e+00,6.2999999999999998e+00,7.5000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,"""D""",
4,3548,"""55566""",55566,"""Rizno""","""UT685""",7.5000000000000000e+01,3,"""D""",3.8000000000000000e+02,5.0000000000000000e-01,...,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,"""D""",
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347975,305476,"""661645""",2,"""XERORTHENTS""","""CA7021""",5.0000000000000000e+01,0,"""B""",1.5240000000000000e+03,5.0000000000000000e-01,...,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,,"""STATSGO"""
347976,305491,"""676914""",1,"""ROCK OUTCROP""","""DC0015""",5.0000000000000000e+01,0,"""D""",1.5240000000000000e+03,5.0000000000000000e-01,...,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,,"""STATSGO"""
347977,305498,"""676924""",1,"""MIDWAY""","""CO0612""",1.8000000000000000e+01,0,"""D""",4.0639999999999998e+02,5.0000000000000000e-01,...,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,,"""STATSGO"""
347978,305520,"""676968""",1,"""ROCK OUTCROP""","""DC0015""",5.0000000000000000e+01,0,"""D""",1.5240000000000000e+03,5.0000000000000000e-01,...,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,0.0000000000000000e+00,,"""STATSGO"""
347979,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [92]:
df.dtypes

OBJECTID       object
MUID           object
SEQN           object
SNAM           object
S5ID           object
                ...
SOL_PH8        object
SOL_PH9        object
SOL_PH10       object
HYDGRP_ORIG    object
Notes          object
Length: 154, dtype: object

In [93]:
df['MUID'].unique()

array(['"49315"', '"50154"', '"50155"', ..., '"2995010"', '"900001"',
       None], dtype=object)

## export to csv

In [88]:
df.to_csv(fname_csv, index = False )